spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: gita
    password: gita
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jwt:
  signingkey: the-man-on-the-silver-mountain